In [2]:
# ==========================================================
# STEP 1: IMPORT SQLITE & CREATE A DATABASE
# ==========================================================

# sqlite3 is built into Python — no pip install needed!

import sqlite3
# Create a connection to a new database file
# This creates a file called 'school.db' in your project folder

conn = sqlite3.connect('school.db')
# Create a cursor — this is your "pen" that writes SQL commands
cursor = conn.cursor()
print("Database 'school.db' created succesfully!")

import sqlite3
import pandas as pd

# Connect fresh
conn = sqlite3.connect('school.db')
cursor = conn.cursor()

# 1. Create tables
cursor.execute('CREATE TABLE IF NOT EXISTS students (student_id INTEGER PRIMARY KEY, first_name TEXT, last_name TEXT, email TEXT, grade_level TEXT, enrollment_date TEXT)')
cursor.execute('CREATE TABLE IF NOT EXISTS courses (course_id INTEGER PRIMARY KEY, course_name TEXT, subject TEXT, credits INTEGER, instructor TEXT)')
cursor.execute('CREATE TABLE IF NOT EXISTS enrollments (enrollment_id INTEGER PRIMARY KEY, student_id INTEGER, course_id INTEGER, semester TEXT, final_grade REAL)')

# 2. Data
students_data = [
    (1, 'Amina', 'Okafor', 'amina@school.edu', 'Year 1', '2025-09-01'),
    (2, 'James', 'Smith', 'james@school.edu', 'Year 2', '2024-09-01'),
    (3, 'Fatima', 'Bello', 'fatima@school.edu', 'Year 1', '2025-09-01'),
    (4, 'David', 'Chen', 'david@school.edu', 'Year 3', '2023-09-01'),
    (5, 'Grace', 'Eze', 'grace@school.edu', 'Year 2', '2024-09-01'),
    (6, 'Omar', 'Hassan', 'omar@school.edu', 'Year 1', '2025-09-01'),
    (7, 'Sarah', 'Williams', 'sarah@school.edu', 'Year 3', '2023-09-01'),
    (8, 'Chidi', 'Nwosu', 'chidi@school.edu', 'Year 2', '2024-09-01'),
    (9, 'Lena', 'Mueller', 'lena@school.edu', 'Year 1', '2025-09-01'),
    (10, 'Kwame', 'Asante', 'kwame@school.edu', 'Year 3', '2023-09-01')
]

courses_data = [
    (101, 'Introduction to Python', 'Computer Science', 3, 'Dr. Adewale'),
    (102, 'Calculus I', 'Mathematics', 4, 'Prof. Schmidt'),
    (103, 'English Composition', 'English', 3, 'Dr. Osei'),
    (104, 'Data Structures', 'Computer Science', 4, 'Dr. Adewale'),
    (105, 'Statistics', 'Mathematics', 3, 'Prof. Rossi')
]

enrollments_data = [
    (1, 1, 101, 'Fall 2025', 88.5),
    (2, 1, 102, 'Fall 2025', 72.0),
    (3, 2, 104, 'Fall 2025', 91.0),
    (4, 2, 105, 'Fall 2025', 65.5),
    (5, 3, 101, 'Fall 2025', 95.0),
    (6, 3, 103, 'Fall 2025', 82.0),
    (7, 4, 104, 'Fall 2025', 78.5),
    (8, 4, 105, 'Fall 2025', 88.0),
    (9, 5, 102, 'Fall 2025', 55.0),
    (10, 5, 103, 'Fall 2025', 70.0),
    (11, 6, 101, 'Fall 2025', 42.0),
    (12, 7, 104, 'Fall 2025', 96.0),
    (13, 8, 102, 'Fall 2025', 73.5),
    (14, 9, 101, 'Fall 2025', 89.0),
    (15, 10, 105, 'Fall 2025', 91.5)
]

# 3. Insert records
cursor.executemany('INSERT OR IGNORE INTO students VALUES (?, ?, ?, ?, ?, ?)', students_data)
cursor.executemany('INSERT OR IGNORE INTO courses VALUES (?, ?, ?, ?, ?)', courses_data)
cursor.executemany('INSERT OR IGNORE INTO enrollments VALUES (?, ?, ?, ?, ?)', enrollments_data)

# 4. Commit changes
conn.commit()

# Helper query function
def run_query(sql):
    return pd.read_sql_query(sql, conn)

print("✅ DATABASE INITIALIZED & POPULATED!")
run_query("SELECT * FROM students")

Database 'school.db' created succesfully!
✅ DATABASE INITIALIZED & POPULATED!

,student_id,first_name,last_name,email,grade_level,enrollment_date
0,1,Amina,Okafor,amina@school.edu,Year 1,2025-09-01
1,2,James,Smith,james@school.edu,Year 2,2024-09-01
2,3,Fatima,Bello,fatima@school.edu,Year 1,2025-09-01
3,4,David,Chen,david@school.edu,Year 3,2023-09-01
4,5,Grace,Eze,grace@school.edu,Year 2,2024-09-01
5,6,Omar,Hassan,omar@school.edu,Year 1,2025-09-01
6,7,Sarah,Williams,sarah@school.edu,Year 3,2023-09-01
7,8,Chidi,Nwosu,chidi@school.edu,Year 2,2024-09-01
8,9,Lena,Mueller,lena@school.edu,Year 1,2025-09-01
9,10,Kwame,Asante,kwame@school.edu,Year 3,2023-09-01

In [8]:
# ==========================================================
# STEP 2: CREATE TABLES (Structure for your data)
# ==========================================================

# TABLE 1: Students
# This defines the columns and what type of data each holds

cursor.execute(''' 
       CREATE TABLE IF NOT EXISTS students (
       student_id INTEGER PRIMARY KEY,
       first_name TEXT,
       last_name TEXT,
       email TEXT,
       grade_level TEXT,
       enrollment_date TEXT
       )
''')

# What each part means:
# INTEGER PRIMARY KEY = unique ID number for each student (auto-generated)
# TEXT = any text/letters
# IF NOT EXISTS = don't crash if table already exists

# TABLE 2: Courses
cursor.execute(''' 
        CREATE TABLE IF NOT EXISTS courses (
        course_id INTEGER PRIMARY KEY,
        course_name TEXT,
        subject TEXT,
        credits INTEGER,
        instructor TEXT
)
''')

# TABLE 3: Enrollments (connects students to courses)

cursor.execute('''  
       CREATE TABLE IF NOT EXISTS enrollments (
       enrollment_id INTEGER PRIMARY KEY,
       student_id INTEGER,
       course_id INTEGER,
       semester TEXT,
       final_grade REAL
       )
 
 ''')
# Save the changes to the database

conn.commit()
print("3 tables created: students, courses and enrollments")

3 tables created: students, courses and enrollments

In [12]:
# ==========================================================
# STEP 3: INSERT DATA INTO TABLES
# ==========================================================

# Insert 10 students
students_data = [
    (1, 'Amina', 'Okafor', 'amina@school.edu', 'Year 1', '2025-09-01'),
    (2, 'James', 'Smith', 'james@school.edu', 'Year 2', '2024-09-01'),
    (3, 'Fatima', 'Bello', 'fatima@school.edu', 'Year 1', '2025-09-01'),
    (4, 'David', 'Chen', 'david@school.edu', 'Year 3', '2023-09-01'),
    (5, 'Grace', 'Eze', 'grace@school.edu', 'Year 2', '2024-09-01'),
    (6, 'Omar', 'Hassan', 'omar@school.edu', 'Year 1', '2025-09-01'),
    (7, 'Sarah', 'Williams', 'sarah@school.edu', 'Year 3', '2023-09-01'),
    (8, 'Chidi', 'Nwosu', 'chidi@school.edu', 'Year 2', '2024-09-01'),
    (9, 'Lena', 'Mueller', 'lena@school.edu', 'Year 1', '2025-09-01'),
    (10, 'Kwame', 'Asante', 'kwame@school.edu', 'Year 3', '2023-09-01')
]
# INSERT INTO = add new rows
# ? = placeholder (prevents SQL injection attacks — security best practice)

cursor.executemany(''' 
       INSERT OR IGNORE INTO students (student_id, first_name, last_name, email, grade_level, enrollment_date)
       VALUES (?, ?, ?, ?, ?, ?)
''', students_data)

# Insert 5 courses
courses_data = [
    (101, 'Introduction to Python', 'Computer Science', 3, 'Dr. Adewale'),
    (102, 'Calculus I', 'Mathematics', 4, 'Prof. Schmidt'),
    (103, 'English Composition', 'English', 3, 'Dr. Osei'),
    (104, 'Data Structures', 'Computer Science', 4, 'Dr. Adewale'),
    (105, 'Statistics', 'Mathematics', 3, 'Prof. Rossi')
]
cursor.executemany(''' 
      INSERT OR IGNORE INTO courses (course_id, course_name, subject, credits, instructor)
      VALUES (?, ?, ?, ?, ?)
''', courses_data)

# Insert 15 enrollments (which student took which course and their grade)
enrollments_data = [
    (1, 1, 101, 'Fall 2025', 88.5),
    (2, 1, 102, 'Fall 2025', 72.0),
    (3, 2, 104, 'Fall 2025', 91.0),
    (4, 2, 105, 'Fall 2025', 65.5),
    (5, 3, 101, 'Fall 2025', 95.0),
    (6, 3, 103, 'Fall 2025', 82.0),
    (7, 4, 104, 'Fall 2025', 78.5),
    (8, 4, 105, 'Fall 2025', 88.0),
    (9, 5, 102, 'Fall 2025', 55.0),
    (10, 5, 103, 'Fall 2025', 70.0),
    (11, 6, 101, 'Fall 2025', 42.0),
    (12, 7, 104, 'Fall 2025', 96.0),
    (13, 8, 102, 'Fall 2025', 73.5),
    (14, 9, 101, 'Fall 2025', 89.0),
    (15, 10, 105, 'Fall 2025', 91.5)
]
cursor.executemany(''' 
       INSERT OR IGNORE INTO enrollments (enrollment_id, student_id, course_id, semester, final_grade)
       VALUES (?, ?, ?, ?, ?)
''', enrollments_data)

# Save everything
conn.commit()
print("✅ Data inserted successfully!")
print("   - 10 students")
print("   - 5 courses")
print("   - 15 enrollments")

✅ Data inserted successfully!
   - 10 students
   - 5 courses
   - 15 enrollments

In [3]:
# ==========================================================
# STEP 4: SQL QUERIES (Asking Questions of Your Data)
# ==========================================================

# Helper function to display results nicely using pandas
import pandas as pd

def run_query(sql):
    """ Runs a SQL query and and displays result as a pandas table """
    return pd.read_sql_query(sql, conn)

# ----- QUERY 1: SELECT (Get all data from a table) -----
# SELECT * means "show me ALL columns"
# FROM students means "from the students table"
print("--- ALL STUDENTS ---")
run_query("SELECT * FROM students")

--- ALL STUDENTS ---

,student_id,first_name,last_name,email,grade_level,enrollment_date
0,1,Amina,Okafor,amina@school.edu,Year 1,2025-09-01
1,2,James,Smith,james@school.edu,Year 2,2024-09-01
2,3,Fatima,Bello,fatima@school.edu,Year 1,2025-09-01
3,4,David,Chen,david@school.edu,Year 3,2023-09-01
4,5,Grace,Eze,grace@school.edu,Year 2,2024-09-01
5,6,Omar,Hassan,omar@school.edu,Year 1,2025-09-01
6,7,Sarah,Williams,sarah@school.edu,Year 3,2023-09-01
7,8,Chidi,Nwosu,chidi@school.edu,Year 2,2024-09-01
8,9,Lena,Mueller,lena@school.edu,Year 1,2025-09-01
9,10,Kwame,Asante,kwame@school.edu,Year 3,2023-09-01

In [4]:
# ----- QUERY 2: SELECT specific columns -----
# Only show names and grade level (not email, not ID)
print("\n--- STUDENT NAMES & GRADE LEVEL ---")
run_query("SELECT first_name, last_name, grade_level FROM students")

--- STUDENT NAMES & GRADE LEVEL ---

  first_name last_name grade_level
0      Amina    Okafor      Year 1
1      James     Smith      Year 2
2     Fatima     Bello      Year 1
3      David      Chen      Year 3
4      Grace       Eze      Year 2
5       Omar    Hassan      Year 1
6      Sarah  Williams      Year 3
7      Chidi     Nwosu      Year 2
8       Lena   Mueller      Year 1
9      Kwame    Asante      Year 3

In [5]:
# ----- QUERY 3: WHERE (Filter rows) -----
# Show only Year 1 students
print("\n--- YEAR 1 STUDENTS ONLY ---")
run_query("SELECT first_name, last_name FROM students WHERE grade_level = 'Year 1'")

--- YEAR 1 STUDENTS ONLY ---

  first_name last_name
0      Amina    Okafor
1     Fatima     Bello
2       Omar    Hassan
3       Lena   Mueller

In [6]:
# ----- QUERY 4: WHERE with numbers -----
# Show enrollments where student scored above 85
print("\n--- HIGH SCORING ENROLLMENTS (>85) ---")
run_query("SELECT student_id, course_id, final_grade FROM enrollments WHERE final_grade > 85")

--- HIGH SCORING ENROLLMENTS (>85) ---

   student_id  course_id  final_grade
0           1        101         88.5
1           2        104         91.0
2           3        101         95.0
3           4        105         88.0
4           7        104         96.0
5           9        101         89.0
6          10        105         91.5

In [7]:
import sqlite3
import pandas as pd

# 1. Connect
conn = sqlite3.connect('school.db')
cursor = conn.cursor()

# 2. Re-create tables cleanly
cursor.execute('CREATE TABLE IF NOT EXISTS students (student_id INTEGER PRIMARY KEY, first_name TEXT, last_name TEXT, email TEXT, grade_level TEXT, enrollment_date TEXT)')
cursor.execute('CREATE TABLE IF NOT EXISTS courses (course_id INTEGER PRIMARY KEY, course_name TEXT, subject TEXT, credits INTEGER, instructor TEXT)')
cursor.execute('CREATE TABLE IF NOT EXISTS enrollments (enrollment_id INTEGER PRIMARY KEY, student_id INTEGER, course_id INTEGER, semester TEXT, final_grade REAL)')

# 3. Data Lists
students_data = [
    (1, 'Amina', 'Okafor', 'amina@school.edu', 'Year 1', '2025-09-01'),
    (2, 'James', 'Smith', 'james@school.edu', 'Year 2', '2024-09-01'),
    (3, 'Fatima', 'Bello', 'fatima@school.edu', 'Year 1', '2025-09-01'),
    (4, 'David', 'Chen', 'david@school.edu', 'Year 3', '2023-09-01'),
    (5, 'Grace', 'Eze', 'grace@school.edu', 'Year 2', '2024-09-01'),
    (6, 'Omar', 'Hassan', 'omar@school.edu', 'Year 1', '2025-09-01'),
    (7, 'Sarah', 'Williams', 'sarah@school.edu', 'Year 3', '2023-09-01'),
    (8, 'Chidi', 'Nwosu', 'chidi@school.edu', 'Year 2', '2024-09-01'),
    (9, 'Lena', 'Mueller', 'lena@school.edu', 'Year 1', '2025-09-01'),
    (10, 'Kwame', 'Asante', 'kwame@school.edu', 'Year 3', '2023-09-01')
]

courses_data = [
    (101, 'Introduction to Python', 'Computer Science', 3, 'Dr. Adewale'),
    (102, 'Calculus I', 'Mathematics', 4, 'Prof. Schmidt'),
    (103, 'English Composition', 'English', 3, 'Dr. Osei'),
    (104, 'Data Structures', 'Computer Science', 4, 'Dr. Adewale'),
    (105, 'Statistics', 'Mathematics', 3, 'Prof. Rossi')
]

enrollments_data = [
    (1, 1, 101, 'Fall 2025', 88.5),
    (2, 1, 102, 'Fall 2025', 72.0),
    (3, 2, 104, 'Fall 2025', 91.0),
    (4, 2, 105, 'Fall 2025', 65.5),
    (5, 3, 101, 'Fall 2025', 95.0),
    (6, 3, 103, 'Fall 2025', 82.0),
    (7, 4, 104, 'Fall 2025', 78.5),
    (8, 4, 105, 'Fall 2025', 88.0),
    (9, 5, 102, 'Fall 2025', 55.0),
    (10, 5, 103, 'Fall 2025', 70.0),
    (11, 6, 101, 'Fall 2025', 42.0),
    (12, 7, 104, 'Fall 2025', 96.0),
    (13, 8, 102, 'Fall 2025', 73.5),
    (14, 9, 101, 'Fall 2025', 89.0),
    (15, 10, 105, 'Fall 2025', 91.5)
]

# 4. Insert cleanly
cursor.executemany('INSERT OR IGNORE INTO students VALUES (?, ?, ?, ?, ?, ?)', students_data)
cursor.executemany('INSERT OR IGNORE INTO courses VALUES (?, ?, ?, ?, ?)', courses_data)
cursor.executemany('INSERT OR IGNORE INTO enrollments VALUES (?, ?, ?, ?, ?)', enrollments_data)

# 5. COMMIT (Saves the changes permanently)
conn.commit()

# Helper function
def run_query(sql):
    return pd.read_sql_query(sql, conn)

# 6. Test Query
print("✅ Verification Check (Students in Database):")
run_query("SELECT first_name, last_name, grade_level FROM students")

✅ Verification Check (Students in Database):

  first_name last_name grade_level
0      Amina    Okafor      Year 1
1      James     Smith      Year 2
2     Fatima     Bello      Year 1
3      David      Chen      Year 3
4      Grace       Eze      Year 2
5       Omar    Hassan      Year 1
6      Sarah  Williams      Year 3
7      Chidi     Nwosu      Year 2
8       Lena   Mueller      Year 1
9      Kwame    Asante      Year 3

In [8]:
# ----- QUERY 5: ORDER BY (Sort results) -----
# Show all enrollments sorted by grade (highest first)
# DESC = descending (highest to lowest)
# ASC = ascending (lowest to highest)
print("\n--- ENROLLMENTS SORTED BY GRADE (Highest First) ---")
run_query("SELECT student_id, course_id, final_grade FROM enrollments ORDER BY final_grade DESC")

--- ENROLLMENTS SORTED BY GRADE (Highest First) ---

    student_id  course_id  final_grade
0            7        104         96.0
1            3        101         95.0
2           10        105         91.5
3            2        104         91.0
4            9        101         89.0
5            1        101         88.5
6            4        105         88.0
7            3        103         82.0
8            4        104         78.5
9            8        102         73.5
10           1        102         72.0
11           5        103         70.0
12           2        105         65.5
13           5        102         55.0
14           6        101         42.0

In [9]:
# ----- QUERY 6: LIMIT (Show only top N results) -----
# Top 3 highest grades
print("\n--- TOP 3 HIGHEST GRADES ---")
run_query("SELECT student_id, course_id, final_grade FROM enrollments ORDER BY final_grade DESC LIMIT 3")

--- TOP 3 HIGHEST GRADES ---

   student_id  course_id  final_grade
0           7        104         96.0
1           3        101         95.0
2          10        105         91.5

In [10]:
# ----- QUERY 7: COUNT, AVG, MAX, MIN (Aggregate functions) -----
# How many students? What's the average grade?
print("\n--- SCHOOL STATISTICS ---")
run_query('''
    SELECT 
        COUNT(*) as total_enrollments,
        ROUND(AVG(final_grade), 1) as average_grade,
        MAX(final_grade) as highest_grade,
        MIN(final_grade) as lowest_grade
    FROM enrollments
''')
# ROUND(..., 1) = round to 1 decimal place
# as = rename the column in the output

--- SCHOOL STATISTICS ---

   total_enrollments  average_grade  highest_grade  lowest_grade
0                 15           78.5           96.0          42.0

In [11]:
# ----- QUERY 8: GROUP BY (Summarize by category) -----
# Average grade per course
print("\n--- AVERAGE GRADE PER COURSE ---")
run_query('''
    SELECT course_id, 
           COUNT(*) as num_students, 
           ROUND(AVG(final_grade), 1) as avg_grade
    FROM enrollments
    GROUP BY course_id
''')

--- AVERAGE GRADE PER COURSE ---

   course_id  num_students  avg_grade
0        101             4       78.6
1        102             3       66.8
2        103             2       76.0
3        104             3       88.5
4        105             3       81.7

In [12]:
# ----- QUERY 9: JOIN (Combine two tables — MOST IMPORTANT!) -----
# Show student names WITH their grades
# JOIN connects tables using a shared column (student_id)
print("\n--- STUDENT NAMES WITH THEIR GRADES ---")
run_query('''
    SELECT 
        s.first_name, 
        s.last_name, 
        c.course_name, 
        e.final_grade
    FROM enrollments e
    JOIN students s ON e.student_id = s.student_id
    JOIN courses c ON e.course_id = c.course_id
    ORDER BY e.final_grade DESC
''')
# e, s, c are "aliases" (nicknames) so we don't type full table names
# ON = the matching column between the two tables

--- STUDENT NAMES WITH THEIR GRADES ---

   first_name last_name             course_name  final_grade
0       Sarah  Williams         Data Structures         96.0
1      Fatima     Bello  Introduction to Python         95.0
2       Kwame    Asante              Statistics         91.5
3       James     Smith         Data Structures         91.0
4        Lena   Mueller  Introduction to Python         89.0
5       Amina    Okafor  Introduction to Python         88.5
6       David      Chen              Statistics         88.0
7      Fatima     Bello     English Composition         82.0
8       David      Chen         Data Structures         78.5
9       Chidi     Nwosu              Calculus I         73.5
10      Amina    Okafor              Calculus I         72.0
11      Grace       Eze     English Composition         70.0
12      James     Smith              Statistics         65.5
13      Grace       Eze              Calculus I         55.0
14       Omar    Hassan  Introduction to Python         42.0

In [13]:
# ----- QUERY 10: JOIN + WHERE (Filter joined data) -----
# Find students who are FAILING (grade < 50)
print("\n--- FAILING STUDENTS (GRADE < 50) ---")
run_query('''
    SELECT 
        s.first_name, 
        s.last_name, 
        c.course_name, 
        e.final_grade
    FROM enrollments e
    JOIN students s ON e.student_id = s.student_id
    JOIN courses c ON e.course_id = c.course_id
    WHERE e.final_grade < 50
''')

--- FAILING STUDENTS (GRADE < 50) ---

  first_name last_name             course_name  final_grade
0       Omar    Hassan  Introduction to Python         42.0

In [14]:
# ==========================================================
# SQL CHEAT SHEET — The 6 Commands You'll Use 95% of the Time
# ==========================================================

cheat_sheet = """
┌─────────────────────────────────────────────────────────┐
│              SQL CHEAT SHEET FOR EDTECH                 │
├─────────────────────────────────────────────────────────┤
│                                                         │
│  SELECT columns    → What data do you want?             │
│  FROM table        → Where is the data?                 │
│  WHERE condition   → Filter specific rows               │
│  GROUP BY column   → Summarize by category              │
│  ORDER BY column   → Sort results (ASC/DESC)            │
│  JOIN table ON     → Combine two tables                 │
│                                                         │
│  EXAMPLE:                                               │
│  SELECT s.first_name, e.final_grade                     │
│  FROM enrollments e                                     │
│  JOIN students s ON e.student_id = s.student_id         │
│  WHERE e.final_grade < 50                               │
│  ORDER BY e.final_grade ASC                             │
│                                                         │
│  AGGREGATES:                                            │
│  COUNT(*)  → How many?                                  │
│  AVG(col)  → Average?                                   │
│  SUM(col)  → Total?                                     │
│  MAX(col)  → Highest?                                   │
│  MIN(col)  → Lowest?                                    │
│                                                         │
└─────────────────────────────────────────────────────────┘
"""
print(cheat_sheet)

┌─────────────────────────────────────────────────────────┐
│              SQL CHEAT SHEET FOR EDTECH                 │
├─────────────────────────────────────────────────────────┤
│                                                         │
│  SELECT columns    → What data do you want?             │
│  FROM table        → Where is the data?                 │
│  WHERE condition   → Filter specific rows               │
│  GROUP BY column   → Summarize by category              │
│  ORDER BY column   → Sort results (ASC/DESC)            │
│  JOIN table ON     → Combine two tables                 │
│                                                         │
│  EXAMPLE:                                               │
│  SELECT s.first_name, e.final_grade                     │
│  FROM enrollments e                                     │
│  JOIN students s ON e.student_id = s.student_id         │
│  WHERE e.final_grade < 50                               │
│  ORDER BY e.final_grade ASC                             │
│                                                         │
│  AGGREGATES:                                            │
│  COUNT(*)  → How many?                                  │
│  AVG(col)  → Average?                                   │
│  SUM(col)  → Total?                                     │
│  MAX(col)  → Highest?                                   │
│  MIN(col)  → Lowest?                                    │
│                                                         │
└─────────────────────────────────────────────────────────┘